Mon Nov 20 14:27:11 CET 2023 Thread[main,5,main] Cleanup action starting
ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:144)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
Cleanup action completed
Mon Nov 20 14:27:11 CET 2023 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Failed to create database 'BDDSAEEsport', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:98)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:142)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Util.java:278)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2541)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:144)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
Caused by: java.sql.SQLException: Failed to create database 'BDDSAEEsport', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)
	... 12 more
Caused by: java.sql.SQLException: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:256)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:400)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:348)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2290)
	... 10 more
Caused by: ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	... 9 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:98)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:256)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:400)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:348)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2290)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2541)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:144)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
Caused by: java.sql.SQLException: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)
	... 14 more
Caused by: ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	... 9 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
java.sql.SQLException: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:256)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:400)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:348)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2290)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2541)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:144)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
Caused by: ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	... 9 more
============= end nested exception, level (2) ===========
============= begin nested exception, level (3) ===========
ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:144)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
============= end nested exception, level (3) ===========
Cleanup action completed
Mon Nov 20 14:27:11 CET 2023 Thread[main,5,main] Cleanup action starting
ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:126)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
Cleanup action completed
Mon Nov 20 14:27:11 CET 2023 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Failed to create database 'BDDSAEEsport', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:98)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:142)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Util.java:278)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2541)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:126)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
Caused by: java.sql.SQLException: Failed to create database 'BDDSAEEsport', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)
	... 12 more
Caused by: java.sql.SQLException: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:256)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:400)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:348)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2290)
	... 10 more
Caused by: ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	... 9 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:98)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:256)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:400)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:348)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2290)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2541)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:126)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
Caused by: java.sql.SQLException: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)
	... 14 more
Caused by: ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	... 9 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
java.sql.SQLException: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:256)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:400)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:348)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2290)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2541)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:126)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
Caused by: ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	... 9 more
============= end nested exception, level (2) ===========
============= begin nested exception, level (3) ===========
ERROR XBM0A: The database directory 'C:\Users\rasoa\Documents\GitHub\sae-gestion-esport\sae-gestion-saison-competition-e-sport\sae_esport\BDDSAEEsport' exists. However, it does not contain the expected 'service.properties' file. Perhaps Derby was brought down in the middle of creating this database. You may want to delete this directory and try creating the database again.
	at org.apache.derby.iapi.error.StandardException.newException(StandardException.java:303)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.vetService(StorageFactoryService.java:710)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$600(StorageFactoryService.java:64)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(StorageFactoryService.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:642)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1740)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1002)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:596)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2534)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:407)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:73)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:51)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Driver40.java:70)
	at org.apache.derby.jdbc.InternalDriver.connect(InternalDriver.java:248)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:126)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at insertValues.main(insertValues.java:15)
============= end nested exception, level (3) ===========
Cleanup action completed
